# Generated by Django 3.0.5 on 2020-04-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200410_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
