# Generated by Django 3.0.5 on 2020-04-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='user',
        ),
    ]
