# Generated by Django 3.0.5 on 2020-04-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_favoritedproduct_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='loves',
            new_name='products',
        ),
    ]
